### ISSUE TITLE
ScalaDSL marker not inherited from traits

### ISSUE THREAD

**Issue by sinwe** [danielwegener/intellij-cucumber-scala#15] opened 2015-12-18 10:10 UTC
Installed this plugin on IntelliJ 15.0.2 with scala plugin installed.
The Feature files are not able to link the steps to the glue code.

**Comment by danielwegener** [comment] 2015-12-18 10:55
Can you confirm the build number 144.2151 (IntelliJ -> Help -> About)?

**Comment by sinwe** [comment] 2015-12-18 11:06
I can only get back with that on Monday. But I've tried with latest
intellij available as of now.

Regards,
Wins

On Fri, Dec 18, 2015, 18:55 Daniel Wegener <notifications@github.com> wrote:

> Can you confirm the build number 144.2151 (IntelliJ -> Help -> About)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danielwegener/intellij-cucumber-scala/issues/15#issuecomment-165747635>
> .
>
-- 

Regards,
Winarto

**Comment by danielwegener** [comment] 2015-12-18 15:53
Cheers! I quickly tried to reproduce the issue but all just *works fine on my machine* with:

- idea 143.1184.17 (15.0.2 ultimate)
- intellij scala 2.0.4
- `info.cukes:cucumber-scala:1.2.4` (as module dependency)

Is this a bug that just occured after the update? Could you retry it with the example module in this repository or provide a minimal example that shows the bug?

**Comment by sinwe** [comment] 2015-12-21 04:21
Hi,

Here is what I can confirm:
* IntelliJ IDEA 143.1187 (15.0.2 ultimate), not sure what the last number is.
* Intellij scala 2.0.4
* info.cukes:cucumber-scala_2.10:1.2.4 (as module dependency). In fact, I tried with both 1.2.0 and 1.2.4.

This is the first time I use cucumber-scala, so I don't know if this occurs prior to this version. Unfortunately I can't get sbt running from my office workstation due to proxy blocking external maven and ivy repo.

I'll try again at home and see if I can reproduce. If i could, I'll provide example.

**Comment by sinwe** [comment] 2015-12-22 06:17
I just downloaded this plugin source code, and realize that it depends on scala 2.11.
Does this work on scala 2.10?

**Comment by sinwe** [comment] 2015-12-22 09:34
Created gist [here](https://gist.github.com/sinwe/b7432758cf2b5784069e)

**Comment by danielwegener** [comment] 2015-12-22 11:50
I see your point. A quick work around is to make `EnglishCucumberSteps` an abstract class or to mix in the `ScalaDSL` trait into `RpnCalculatorStepDefinitions` directly.

I'll rename this issue to __ScalaDSL marker not inherited from traits__

**Comment by danielwegener** [comment] 2015-12-22 11:59
And thanks for the report and your effort to make it reproducible :). That's really helpful!

**Comment by danielwegener** [comment] 2015-12-22 14:14
fixed in 0.3.3 (on the way to the jetbrains plugin repository)

**Comment by sinwe** [comment] 2015-12-22 14:20
Does 0.3.3 also fix the issue with multiline step?

**Comment by danielwegener** [comment] 2015-12-22 14:24
Oh sorry I completely read over that one. I gonna create a seperate ticket for that.

**Comment by danielwegener** [comment] 2015-12-22 14:33
Any Idea how it should look like? You mean something like this?
```scala
When(
    """I use
      |multiline
    """.stripMargin) {
    ???
  }
```
A bit hard because `.stripMargin` would have to be _executed_ while searching for glue code. As with java-annotations, the current implementation only allows real string literals to be used in step definitions.

**Comment by sinwe** [comment] 2015-12-22 14:37
Yeah, something like that. Or to put simpler, something like this
```
When("I use" +
    "multiline"){
       ???
   }
```

**Comment by sinwe** [comment] 2017-03-24 04:50
This seems to happen again with IntelliJ IDEA 2017.1

**Comment by danielwegener** [comment] 2017-03-24 06:23
Thats not cool. Maybe the scala PSI api has changed.

**Comment by pbyrne84** [comment] 2017-03-24 20:47
I think there is something going on weird..

If debug 
  @NotNull
  override val getStepFileType: BDDFrameworkType = {
    classOf[ScalaFileType].getDeclaredFields.foreach{ field =>
      println(field.getName)
    }


    new BDDFrameworkType(ScalaFileType.SCALA_FILE_TYPE)
  }

the fields match this implementation 
https://github.com/JetBrains/intellij-scala/blob/1d3f21e7368216b0e0b26ad7b39ca1c978c26ab7/src/org/jetbrains/plugins/scala/ScalaFileType.java

class org.jetbrains.plugins.scala.ScalaFileType
INSTANCE
WORKSHEET_EXTENSION

Not the one in the project
https://github.com/scalatest/intellij-scala-old/blob/master/src/org/jetbrains/plugins/scala/ScalaFileType.java

and also the one intellij includes as default in a new scala plugin in project

I might be wrong and it is a wild goose chase.. The easiest way is to rip the jars out that idea is actually using and put them somewhere you can manually customise the jdk

Anyway hope this helps. Trying to do analyse plugin development on a Mac which wants to hide everything in finder is not enjoyable :(

I'll have another look on Monday as  we really depend on this plugin :)

**Comment by pbyrne84** [comment] 2017-03-27 18:14
Okay I have created a repo with the new scala plugin zipped up to go over the old one 

https://github.com/pbyrne84/scala-cucumber-deps
There is also a compiled plugin jar that now works

your travis will likely boo boo because it needs the to use this 

https://github.com/pbyrne84/scala-cucumber-deps/blob/master/scala-plugin.zip

not the one downloaded by sbt updateIdea

**Comment by sinwe** [comment] 2017-03-27 22:51
Apparently someone just raise the same issue [here](https://github.com/danielwegener/intellij-cucumber-scala/issues/26l)

**Comment by pbyrne84** [comment] 2017-03-28 10:45
Okay I fixed the dependency in the pull request so no monkey dancing needed
https://github.com/danielwegener/intellij-cucumber-scala/pull/27

**Comment by danielwegener** [comment] 2017-03-30 13:54
I think we can close this zombie, the cause is not related with trait inheritance (follow up in #26 ).

**Closed by danielwegener** 2017-03-30 13:54 UTC
Labels: bug, help wanted

**Comment by sinwe** [comment] 2017-06-20 15:24
The same issue happens again with 2017.2 EAP.
